apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "csye7125.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csye7125.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csye7125.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag | default .Chart.AppVersion }}"
          env:
            {{- range .Values.postgres.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /var/lib/mydb
      volumes:
        - name: data
          emptyDir: {}